# This configuration file will make Travis CI compile our PDF and force-push it
# back to the repository. 

# This *wonderful* hack is credited to Dan Foreman-Mackey (GitHub: @dfm / Twitter: @exoplaneteer)
# and David W. Hogg (GitHub/Twitter: @davidwhogg) on the repository:
#    https://github.com/davidwhogg/mcmc/

# This hack has been modified slightly to push pdfs to <branch>-pdf

sudo: true

language: python

env:
    matrix:
        - PYTHON_VERSION=3.6

install:
 - wget https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu && chmod +x ./install-tl-ubuntu
 - sudo ./install-tl-ubuntu
 - sudo /opt/texbin/tlmgr init-usertree
 - sudo /opt/texbin/tlmgr update --all
 - sudo /opt/texbin/tlmgr update unicode-math
 - sudo /opt/texbin/tlmgr update xetex
 - "export PATH=$PATH:/opt/texbin"

script:
    - git config --get remote.origin.url
    - make

after_success: |
    if [[ "$PYTHON_VERSION" == "3.6" ]] && [ -n "$GITHUB_API_KEY" ]; then
        # make sure we are in the parent directory of the repository
        cd $TRAVIS_BUILD_DIR
        git checkout --orphan $TRAVIS_BRANCH-pdf
        git rm -rf .
        # Re-name the PDF so that the filename is searchable when it is downloaded
        mv cv.pdf andrew-casey-cv.pdf
        git add -f andrew-casey-cv.pdf
        git -c user.name='travis' -c user.email='travis' commit -m init
        git push -q -f https://andycasey:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
    fi

notifications:
    email:
       on_success: change
       on_failure: always
